version: '3.8'
services:

  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/shopper_taxi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/shopper_taxi
      PORT: 8080
    command: sh -c "./migrate.sh"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://backend:8080
    ports:
      - "80:80"
    env_file:
      - ./.env
    environment:
      REACT_APP_API_URL: http://backend:8080
      REACT_APP_GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - backend

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopper_taxi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
